### ISSUE TITLE
Spaces can break colorization

### ISSUE THREAD

**Issue by cfjedimaster** [IBM-Bluemix/vscode-log-output-colorizer#14]
Check out how the color 'breaks' at the space in "My Space":

![image](https://cloud.githubusercontent.com/assets/393660/22661687/ed44dfda-ec6b-11e6-90ec-873700ca267f.png)

I'm assuming that's not supposed to happen?

**Comment by triceam** [comment]
This is a tough one to fix.  How do you tell the difference between spaces in a regular sentence that contains an email address?  Unfortunately I'm not sure the general purpose nature of this extension can fix that particular use case.

**Comment by cfjedimaster** [comment]
Based on what you told me (that it has to be a regex, and not 'logic'), I agree this would be too difficult to fix. Close if you want. :)

**Comment by triceam** [comment]
Yup, it's all based on general purpose regex.  I don't think there is much I can do for this one without breaking a lot of other things or making it extremely complicated (and probably fragile).  I will see if I can improve regex in general.
