### ISSUE TITLE
Output sometimes not colorized

### ISSUE THREAD

**Issue by oliversalzburg** [IBM-Bluemix/vscode-log-output-colorizer#19]
I have two projects, both have an identical `tasks.json`. When I run project A, the output of the command is colorized:
![image](https://user-images.githubusercontent.com/1658949/32552692-1220c3da-c495-11e7-95eb-3b3fe191855d.png)

When I run it in project B, the output is not colorized:
![image](https://user-images.githubusercontent.com/1658949/32552709-1f6b91b4-c495-11e7-91a3-41a44493e182.png)

The `tasks.json` is this:
```json
{
	"version": "0.1.0",
	"command": "bash.exe",
	"args": [
		"-c"
	],
	"isShellCommand": true,
	"tasks": [
		{
			"taskName": "Build and watch",
			"suppressTaskName": true,
			"args": [
				"compile watch"
			],
			"isBackground": true,
			"problemMatcher": [
				"$eslint-stylish"
			]
		}
	]
}
```

I can't figure out what the difference is or could be.

**Comment by triceam** [comment]
There's most likely another VS Code extension that is overriding the colorization in the Output panel.  There can only be one active colorizer in the output channel at any time - this is a limitation with VS Code itself. Its been reported that the Python, Code Runner, and Quokka extensions will cause conflicts.  There are also a few others that I can't remember the names of off hand.  If you want the colorizer to have precedence, then you might have to disable other extensions.
