### ISSUE TITLE
Output colorizer not working

### ISSUE THREAD

**Issue by AnhQuanTran** [IBM-Bluemix/vscode-log-output-colorizer#21]
Hello
I installed extension output colorizer and reload visual studio code after that. But it is not work.
I use visual studio code version 1.15.1 x64 on windows 10 home
Other extensions installed:
- 1337 theme
- c/c++
- python
- code runner
- nomo dark icon 
- vscode icon

![image](https://user-images.githubusercontent.com/21956433/36781447-7a18fabe-1ca8-11e8-948e-7f9dc35641df.png)

how to fix it
Thank you for help

**Comment by meydjer** [comment]
Same here.

Visual Studio Code v1.20.1 on Linux Fedora 27 x64

Other extensions installed:
- Better TOML
- Earthsong Theme
- Go
- Vim

![1503743_442328547_33403086](https://user-images.githubusercontent.com/584186/36951092-0e2a6a84-1fde-11e8-8976-e9b5e6e67208.png)

**Comment by dmaglio** [comment]
same issue for me... visual studio code v1.21.0 x86 on windows 7 x86 and base16 color theme
![capture](https://user-images.githubusercontent.com/446573/37391913-08ed7d5e-276d-11e8-8e7a-103ef6053880.PNG)
color works until that point...

**Comment by nonameolsson** [comment]
Confirmed, doesn't work with VS Code 1.21.

**Comment by AnhQuanTran** [comment]
Cause python extension. Remove it or disable & restart.

**Comment by dmaglio** [comment]
@AnhQuanTran  i don't have any python extension

**Comment by xiaofengShi** [comment]
the same error ,mac+vscode1.2.1, how to fix it

**Comment by brentmitchell25** [comment]
I had to disable two extensions for it to work: [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) and [Quokka.js](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode)

**Comment by donniean** [comment]
the same

**Comment by triceam** [comment]
Wow, all the way back from Feb and I'm just now seeing this issue... too many notifications.  :) 

Above comments are correct.  There's most likely another VS Code extension that is overriding the colorization in the Output panel.  There can only be one active colorizer in the output channel at any time - this is a limitation with VS Code itself.  As mentioned above, the Python, Code Runner, and Quokka extensions will cause conflicts.  There are also a few others that I can't remember the names of off hand.  If you want the colorizer to have precedence, then you might have to disable other extensions.

**Comment by dmaglio** [comment]
new update: that "error" show in windows when i use git bash instead Windows cmd. maybe it's a git bash issue?

**Comment by fredThem** [comment]
> I had to disable two extensions for it to work: [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) and [Quokka.js](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode)

Disabling Code Runner alone fixed it for me

**Comment by Leonid-98** [comment]
> > I had to disable two extensions for it to work: [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) and [Quokka.js](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode)
> 
> Disabling Code Runner alone fixed it for me

Same for me

**Comment by EricDuminil** [comment]
> I had to disable two extensions for it to work: [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) and [Quokka.js](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode)

That's really too bad, because most of my output content comes from CodeRunner. :-/ If I have to choose between CodeRunner and OutputColorizer, I'll sadly stick to CodeRunner.

**Comment by triceam** [comment]
Unfortunately that's how it works in VS Code, and is beyond our control.  You can only have one extension at a time that actively colorizes the output panel.  The way they work is a bit of a hack in the first place, and it wasn't designed to allow for multiple colorization plugins.
