### ISSUE TITLE
Not wokring!

### ISSUE THREAD

**Issue by sumikum7** [IBM-Bluemix/vscode-log-output-colorizer#22]
Not working in vscode 1.23 on max OS..if not a solution try giving me a suggestion !

**Comment by triceam** [comment]
There's most likely another VS Code extension that is overriding the colorization in the Output panel.  There can only be one active colorizer in the output channel at any time - this is a limitation with VS Code itself.  It's been reported that the Python, Code Runner, and Quokka extensions will cause conflicts.  If you want the colorizer to have precedence, then you might have to disable other extensions.

**Comment by sumikum7** [comment]
that can be a reason.will try and let you know !Thanks...
