### ISSUE TITLE
[FR] link/file detection

### ISSUE THREAD

**Issue by farfromrefug** [IBM-Bluemix/vscode-log-output-colorizer#8]
I know it's kind of out of that extention's name scope but as you already regex the output ...
Would be awesome to detect file/links/errors in output

**Comment by triceam** [comment]
What do you mean by "file/links/errors in output"?  this should already work for the output panel.  Do you mean the Debug Console?

**Comment by farfromrefug** [comment]
Oh sorry i mean detect things like this:
```
/Volumes/data/dev/Movea/mtools/trunk/common/Models/mtuserprofile.cpp:252:122: error: invalid operands to binary expression ('basic_ostream<char, std::__1::char_traits<char> >' and 'std::vector<std::string>'
      (aka 'vector<basic_string<char, char_traits<char>, allocator<char> > >'))
```
This would be awesome, that way you can go directly at the source of the error.
The thing is that i know there are multiple ways of showing it. But getting a way to link to errors from the output would be such a great help.

**Comment by ArtemGovorov** [comment]
> this should already work for the output panel.

It does work without the extension, so the extension seem to break it. When I install the extension, I get colours, but the built-in link detection doesn't work anymore.

**Comment by triceam** [comment]
I still see clickable links, at least for URLs.  Ex: 

![image](https://cloud.githubusercontent.com/assets/974294/18168722/1b79e56c-7025-11e6-8c2c-83e0af92d84a.png)

and 

![image](https://cloud.githubusercontent.com/assets/974294/18168742/34cbcc10-7025-11e6-915f-21b6e338e116.png)

Are you seeing this specifically for filesystem links?   Or, do you mean that this used to get highlighted?

```/Volumes/data/dev/Movea/mtools/trunk/common/Models/mtuserprofile.cpp```

**Comment by ArtemGovorov** [comment]
> Are you seeing this specifically for filesystem links?

Correct, for absolute paths like `/a/b/c/file.txt`.

**Comment by triceam** [comment]
ok, thx.  I'll have to look into this one...

**Comment by twlamb** [comment]
Any movement on this? We have something like `c:\Some\Path\to\file.ext:233:38` which normally is picked up as a link by VSCode, but once I install this extension, it's no longer a link.

**Comment by felipegtx** [comment]
I too am interested in this feature/fix!

**Comment by triceam** [comment]
Thanks everyone - I totally forgot about this one.   let me see what I can do...

**Comment by farfromrefug** [comment]
I actually found the fix for this, and its really easy!
Simply change your language id from ```log``` to ```Log```. This is what vscode expects

**Comment by twlamb** [comment]
Nice @farfromrefug - I've sent a PR with the fix!

**Comment by triceam** [comment]
Nice find!  I am away until Monday, but will check it out (and hopefully push a release) when I get back.

**Comment by triceam** [comment]
Just pushed a build with this fix.  Can you pull from the marketplace and verify for me?  Thx

**Comment by triceam** [comment]
Its working for me for both http:// and file:// URIs.  Not sure about the other error conditions people were seeing.

**Comment by triceam** [comment]
@ArtemGovorov @twlamb with the colorizer extension uninstalled, Either I'm blind, or I don't see links like this getting recognized: `/a/b/c/file.txt`   Is there some other extension you have installed that might be recognizing them?

I've tried both `.log` files and the `output` panel.   Can anyone confirm if this fixed worked?   Only http(s) and file URIs appear for me.

**Comment by twlamb** [comment]
I'd guess if VSCode doesn't make them links w/o your extension, not sure how you could make them, the only thing I noticed is VSCode tags links with the class "detected-link".

Things such as "c:/whatever/path/file.txt" get picked up just fine as well as "c:/whatever/path/file.txt:13:23"

**Comment by triceam** [comment]
To clarify, those windows file paths are working for you with the Colorizer extension?   I'm on a mac, and they don't get recognized for me.

**Comment by twlamb** [comment]
Yes they are working with the Colorizer extension on Windows.

**Comment by triceam** [comment]
Thanks!  I'll consider this issue closed then. 😄
